improve docker build log-3

diff --git a/Jenkinsfile_stable b/Jenkinsfile_stable
--- a/Jenkinsfile_stable
+++ b/Jenkinsfile_stable
@@ -61,7 +61,7 @@ pipeline {
                 echo '===== [DOCKER IMAGE BUILD] Stage Started ====='
                 echo "Building Docker image: sithuj/assignment2_22466972:${BUILD_NUMBER}"
                 sh '''
-                  docker build -t sithuj/assignment2_22466972:${BUILD_NUMBER} . | tee docker-build.log || { echo "Docker image build failed, check docker-build.log for details"; exit 1; }
+                docker build -t sithuj/assignment2_22466972:${BUILD_NUMBER} . 2>&1 | tee docker-build.log || { echo "Docker image build failed, check docker-build.log for details"; exit 1; }
                 '''
                 echo 'Docker image build finished successfully.'
                 echo '===== [DOCKER IMAGE BUILD] Stage Completed ====='
